import {
  Gym,
  GymGradeScale,
  Sector,
  WallBoulder,
  Ascent,
  BoulderRating,
  UserProfile,
  BoulderInput,
} from '../types/boulder';

// -------------------------------------------------------------
// Seed Gym, Scales & Sectors (Minimum Boulder Zürich)
// -------------------------------------------------------------
export const SEED_GYM: Gym = {
  id: 'gym-minimum-zh',
  name: 'Minimum Boulder Zürich',
  city: 'Zürich',
  address: 'Flüelastrasse 31, 8048 Zürich',
  createdBy: 'user-admin-1',
  createdAt: '2026-09-01T10:00:00Z',
};

export const SEED_6A_PLUS_GRADE_SCALES: GymGradeScale[] = [
  { id: 'scale_6a_gelb', gymId: 'gym-6a-plus', colorName: 'Gelb', colorHex: '#eab308', difficultyLabel: 'Sehr leicht', fontRangeMin: '3', fontRangeMax: '4', sortOrder: 1 },
  { id: 'scale_6a_gruen', gymId: 'gym-6a-plus', colorName: 'Grün', colorHex: '#22c55e', difficultyLabel: 'Leicht', fontRangeMin: '5', fontRangeMax: '5+', sortOrder: 2 },
  { id: 'scale_6a_blau', gymId: 'gym-6a-plus', colorName: 'Blau', colorHex: '#3b82f6', difficultyLabel: 'Mittel', fontRangeMin: '6A', fontRangeMax: '6B+', sortOrder: 3 },
  { id: 'scale_6a_rot', gymId: 'gym-6a-plus', colorName: 'Rot', colorHex: '#ef4444', difficultyLabel: 'Schwer', fontRangeMin: '6C', fontRangeMax: '7A+', sortOrder: 4 },
  { id: 'scale_6a_schwarz', gymId: 'gym-6a-plus', colorName: 'Schwarz', colorHex: '#1e293b', difficultyLabel: 'Sehr schwer', fontRangeMin: '7B', fontRangeMax: '7C+', sortOrder: 5 },
  { id: 'scale_6a_weiss', gymId: 'gym-6a-plus', colorName: 'Weiß', colorHex: '#f8fafc', difficultyLabel: 'Extrem', fontRangeMin: '8A', fontRangeMax: '8B', sortOrder: 6 },
  { id: 'scale_6a_lila', gymId: 'gym-6a-plus', colorName: 'Lila', colorHex: '#a855f7', difficultyLabel: 'Elite', fontRangeMin: '8B+', fontRangeMax: '8C+', sortOrder: 7 },
];

export const SEED_GRADE_SCALES: GymGradeScale[] = [
  { id: 'scale-green', gymId: 'gym-minimum-zh', colorName: 'Grün', colorHex: '#22c55e', difficultyLabel: 'Leicht', fontRangeMin: '4a', fontRangeMax: '5b', sortOrder: 1 },
  { id: 'scale-blue', gymId: 'gym-minimum-zh', colorName: 'Blau', colorHex: '#3b82f6', difficultyLabel: 'Fortgeschritten', fontRangeMin: '5c', fontRangeMax: '6b', sortOrder: 2 },
  { id: 'scale-yellow', gymId: 'gym-minimum-zh', colorName: 'Gelb', colorHex: '#eab308', difficultyLabel: 'Sportlich', fontRangeMin: '6b+', fontRangeMax: '7a', sortOrder: 3 },
  { id: 'scale-red', gymId: 'gym-minimum-zh', colorName: 'Rot', colorHex: '#ef4444', difficultyLabel: 'Schwer', fontRangeMin: '7a+', fontRangeMax: '7b+', sortOrder: 4 },
  { id: 'scale-black', gymId: 'gym-minimum-zh', colorName: 'Schwarz', colorHex: '#1e293b', difficultyLabel: 'Sehr schwer', fontRangeMin: '7c', fontRangeMax: '8a', sortOrder: 5 },
  { id: 'scale-white', gymId: 'gym-minimum-zh', colorName: 'Weiß', colorHex: '#f8fafc', difficultyLabel: 'Elite', fontRangeMin: '8a+', fontRangeMax: '8b+', sortOrder: 6 },
  ...SEED_6A_PLUS_GRADE_SCALES
];

export const SEED_SECTORS: Sector[] = [
  {
    id: 'sector-overhang',
    gymId: 'gym-minimum-zh',
    name: 'Überhang 45°',
    wallPhotoUrl: '/images/walls/overhang.jpg',
    sortOrder: 1,
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'sector-slab',
    gymId: 'gym-minimum-zh',
    name: 'Platte (Slab & Balance)',
    wallPhotoUrl: '/images/walls/slab.jpg',
    sortOrder: 2,
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'sector-roof',
    gymId: 'gym-minimum-zh',
    name: 'Wettkampf-Dach & Cave',
    wallPhotoUrl: '/images/walls/roof.jpg',
    sortOrder: 3,
    createdAt: '2026-09-01T10:00:00Z',
  },
];

// -------------------------------------------------------------
// Seed Wall Boulders (21 boulders: 7 per sector, active & archived)
// -------------------------------------------------------------
export const SEED_EXISTING_BOULDERS: WallBoulder[] = [
  // --- Sector 1: Überhang 45° ---
  {
    id: 'boulder-existing-1',
    sectorId: 'sector-overhang',
    gradeScaleId: 'scale-blue',
    positionX: 0.35,
    positionY: 0.42,
    name: 'Dyno King',
    notes: 'Dynamischer Sprung an die Leiste',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 3, balance: 2, koordination: 4, flexibilitaet: 2 },
    createdAt: '2026-08-25T14:00:00Z',
    publishedAt: '2026-08-25T18:00:00Z',
  },
  {
    id: 'boulder-existing-2',
    sectorId: 'sector-overhang',
    gradeScaleId: 'scale-yellow',
    positionX: 0.68,
    positionY: 0.55,
    name: 'Heel-Hook Madness',
    notes: 'Körperspannung am Untergriff',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 3, kraft: 3, technik: 5, balance: 4, koordination: 3, flexibilitaet: 4 },
    createdAt: '2026-08-25T14:30:00Z',
    publishedAt: '2026-08-25T18:00:00Z',
  },
  {
    id: 'boulder-overhang-3',
    sectorId: 'sector-overhang',
    gradeScaleId: 'scale-red',
    positionX: 0.22,
    positionY: 0.30,
    name: 'Power-Leiste',
    notes: 'Kleine Leisten im 45° Überhang',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 3, kraft: 5, technik: 4, balance: 2, koordination: 2, flexibilitaet: 3 },
    createdAt: '2026-08-26T10:00:00Z',
    publishedAt: '2026-08-26T14:00:00Z',
  },
  {
    id: 'boulder-overhang-4',
    sectorId: 'sector-overhang',
    gradeScaleId: 'scale-blue',
    positionX: 0.80,
    positionY: 0.65,
    name: 'Zangengriff Traverse',
    notes: 'Winklige Pinches und weite Züge',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 3, balance: 3, koordination: 3, flexibilitaet: 2 },
    createdAt: '2026-08-27T11:00:00Z',
    publishedAt: '2026-08-27T15:00:00Z',
  },
  {
    id: 'boulder-overhang-5',
    sectorId: 'sector-overhang',
    gradeScaleId: 'scale-green',
    positionX: 0.50,
    positionY: 0.75,
    name: 'Blocker-Kante',
    notes: 'Große Henkel zum Warmklettern',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 3, kraft: 3, technik: 3, balance: 2, koordination: 2, flexibilitaet: 2 },
    createdAt: '2026-08-28T09:00:00Z',
    publishedAt: '2026-08-28T12:00:00Z',
  },
  {
    id: 'boulder-overhang-6',
    sectorId: 'sector-overhang',
    gradeScaleId: 'scale-red',
    positionX: 0.45,
    positionY: 0.20,
    name: 'Der Rote Bulle',
    notes: 'Maximalkraft-Züge ohne Rastposition',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 3, kraft: 5, technik: 4, balance: 2, koordination: 3, flexibilitaet: 2 },
    createdAt: '2026-08-28T10:30:00Z',
    publishedAt: '2026-08-28T13:30:00Z',
  },
  {
    id: 'boulder-overhang-archived-1',
    sectorId: 'sector-overhang',
    gradeScaleId: 'scale-yellow',
    positionX: 0.60,
    positionY: 0.40,
    name: 'Retro-Kante 2025',
    notes: 'Abgeschraubte Legende am Pfeiler',
    setterId: 'setter-1',
    status: 'archived',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 4, balance: 3, koordination: 2, flexibilitaet: 3 },
    createdAt: '2026-07-01T10:00:00Z',
    publishedAt: '2026-07-01T14:00:00Z',
    archivedAt: '2026-08-15T18:00:00Z',
  },

  // --- Sector 2: Platte (Slab & Balance) ---
  {
    id: 'boulder-slab-1',
    sectorId: 'sector-slab',
    gradeScaleId: 'scale-green',
    positionX: 0.25,
    positionY: 0.65,
    name: 'Reibungstraum',
    notes: 'Nur auf Reibung stehen',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 1, kraftausdauer: 3, kraft: 1, technik: 4, balance: 5, koordination: 2, flexibilitaet: 4 },
    createdAt: '2026-08-26T11:00:00Z',
    publishedAt: '2026-08-26T15:00:00Z',
  },
  {
    id: 'boulder-slab-2',
    sectorId: 'sector-slab',
    gradeScaleId: 'scale-blue',
    positionX: 0.45,
    positionY: 0.48,
    name: 'Messers Schneide',
    notes: 'Kleine Tritte, saubere Gewichtsverlagerung',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 3, kraft: 2, technik: 5, balance: 5, koordination: 3, flexibilitaet: 4 },
    createdAt: '2026-08-26T12:00:00Z',
    publishedAt: '2026-08-26T16:00:00Z',
  },
  {
    id: 'boulder-slab-3',
    sectorId: 'sector-slab',
    gradeScaleId: 'scale-yellow',
    positionX: 0.70,
    positionY: 0.38,
    name: 'Körperschwerpunkt',
    notes: 'Hoher Antritt und delikate Balance',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 3, kraft: 2, technik: 5, balance: 5, koordination: 3, flexibilitaet: 5 },
    createdAt: '2026-08-27T14:00:00Z',
    publishedAt: '2026-08-27T18:00:00Z',
  },
  {
    id: 'boulder-slab-4',
    sectorId: 'sector-slab',
    gradeScaleId: 'scale-red',
    positionX: 0.35,
    positionY: 0.28,
    name: 'Mikrotropfen',
    notes: 'Fast grifflos, nur Sloper-Volumen',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 3, kraft: 3, technik: 5, balance: 5, koordination: 4, flexibilitaet: 4 },
    createdAt: '2026-08-27T15:00:00Z',
    publishedAt: '2026-08-27T19:00:00Z',
  },
  {
    id: 'boulder-slab-5',
    sectorId: 'sector-slab',
    gradeScaleId: 'scale-blue',
    positionX: 0.58,
    positionY: 0.72,
    name: 'Zirkus-Stepper',
    notes: 'Koordination über drei Volumen',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 3, kraft: 2, technik: 4, balance: 4, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-08-28T11:00:00Z',
    publishedAt: '2026-08-28T15:00:00Z',
  },
  {
    id: 'boulder-slab-6',
    sectorId: 'sector-slab',
    gradeScaleId: 'scale-green',
    positionX: 0.15,
    positionY: 0.80,
    name: 'Platten-Finesse',
    notes: 'Leichter Einstieg mit schöner Fußarbeit',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 1, kraftausdauer: 3, kraft: 1, technik: 3, balance: 4, koordination: 2, flexibilitaet: 3 },
    createdAt: '2026-08-29T09:30:00Z',
    publishedAt: '2026-08-29T13:00:00Z',
  },
  {
    id: 'boulder-slab-archived-1',
    sectorId: 'sector-slab',
    gradeScaleId: 'scale-yellow',
    positionX: 0.82,
    positionY: 0.30,
    name: 'Die Glatte Wand',
    notes: 'Ehemaliges Platten-Projekt',
    setterId: 'setter-1',
    status: 'archived',
    radar: { maximalkraft: 2, kraftausdauer: 3, kraft: 2, technik: 5, balance: 5, koordination: 3, flexibilitaet: 4 },
    createdAt: '2026-07-10T11:00:00Z',
    publishedAt: '2026-07-10T15:00:00Z',
    archivedAt: '2026-08-18T16:00:00Z',
  },

  // --- Sector 3: Wettkampf-Dach & Cave ---
  {
    id: 'boulder-roof-1',
    sectorId: 'sector-roof',
    gradeScaleId: 'scale-blue',
    positionX: 0.30,
    positionY: 0.70,
    name: 'Fledermaus-Hook',
    notes: 'Toe-Hook Entlastung im Dach',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 4, balance: 3, koordination: 3, flexibilitaet: 5 },
    createdAt: '2026-08-28T13:00:00Z',
    publishedAt: '2026-08-28T17:00:00Z',
  },
  {
    id: 'boulder-roof-2',
    sectorId: 'sector-roof',
    gradeScaleId: 'scale-yellow',
    positionX: 0.52,
    positionY: 0.55,
    name: 'Dach-Kompressor',
    notes: 'Gegendruck auf zwei große Sloper',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 3, kraft: 5, technik: 4, balance: 2, koordination: 3, flexibilitaet: 3 },
    createdAt: '2026-08-28T14:00:00Z',
    publishedAt: '2026-08-28T18:00:00Z',
  },
  {
    id: 'boulder-roof-3',
    sectorId: 'sector-roof',
    gradeScaleId: 'scale-red',
    positionX: 0.75,
    positionY: 0.42,
    name: 'Wettkampf-Sprung',
    notes: 'Dynamischer Paddle-Dyno zur Kante',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 3, balance: 2, koordination: 5, flexibilitaet: 3 },
    createdAt: '2026-08-29T10:00:00Z',
    publishedAt: '2026-08-29T14:00:00Z',
  },
  {
    id: 'boulder-roof-4',
    sectorId: 'sector-roof',
    gradeScaleId: 'scale-black',
    positionX: 0.40,
    positionY: 0.25,
    name: 'Cave Ausstiegs-Crux',
    notes: 'Extrem harter Heel-Hook Ausstieg',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 3, kraft: 5, technik: 5, balance: 3, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-08-29T11:00:00Z',
    publishedAt: '2026-08-29T15:00:00Z',
  },
  {
    id: 'boulder-roof-5',
    sectorId: 'sector-roof',
    gradeScaleId: 'scale-blue',
    positionX: 0.65,
    positionY: 0.68,
    name: 'Körperspannung Pur',
    notes: 'Füße dürfen nicht abrutschen',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 3, balance: 2, koordination: 2, flexibilitaet: 3 },
    createdAt: '2026-08-30T09:00:00Z',
    publishedAt: '2026-08-30T13:00:00Z',
  },
  {
    id: 'boulder-roof-6',
    sectorId: 'sector-roof',
    gradeScaleId: 'scale-green',
    positionX: 0.20,
    positionY: 0.82,
    name: 'Dach-Einstieg',
    notes: 'Gute Griffe durch die Schräge',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 3, kraft: 3, technik: 3, balance: 2, koordination: 2, flexibilitaet: 2 },
    createdAt: '2026-08-30T10:00:00Z',
    publishedAt: '2026-08-30T14:00:00Z',
  },
  {
    id: 'boulder-roof-archived-1',
    sectorId: 'sector-roof',
    gradeScaleId: 'scale-yellow',
    positionX: 0.50,
    positionY: 0.40,
    name: 'Horizontale Hölle',
    notes: 'Klassiker der letzten Saison',
    setterId: 'setter-1',
    status: 'archived',
    radar: { maximalkraft: 5, kraftausdauer: 3, kraft: 5, technik: 4, balance: 2, koordination: 3, flexibilitaet: 3 },
    createdAt: '2026-07-15T12:00:00Z',
    publishedAt: '2026-07-15T16:00:00Z',
    archivedAt: '2026-08-20T17:00:00Z',
  },
];

// -------------------------------------------------------------
// Seed Profiles
// -------------------------------------------------------------
export const SEED_PROFILES: UserProfile[] = [
  { id: 'user-boris', nickname: 'Boris', createdAt: '2026-05-15T10:00:00Z' },
  { id: 'admin-6aplus', nickname: 'Admin6APlus', createdAt: '2026-05-15T10:00:00Z' },
  { id: 'schrauber-6aplus', nickname: 'Schrauber6aPlus', createdAt: '2026-05-15T10:00:00Z' },
  { id: 'hans-kletterer', nickname: 'HansDereinfacheKletterer', createdAt: '2026-05-15T10:00:00Z' },
  { id: 'admin-minimum', nickname: 'AdminMinimum', createdAt: '2026-05-15T10:00:00Z' },
  { id: 'schrauber-minimum', nickname: 'Schrauber Minimum', createdAt: '2026-05-15T10:00:00Z' },
];

// -------------------------------------------------------------
// Seed Ascents (Community & Boris's session logs)
// -------------------------------------------------------------
export const SEED_ASCENTS: Ascent[] = [
  { id: 'ascent-1', userId: 'hans-kletterer', userNickname: 'HansDereinfacheKletterer', boulderId: 'boulder-existing-1', type: 'flash', createdAt: '2026-09-02T16:30:00Z' },
  { id: 'ascent-2', userId: 'admin-minimum', userNickname: 'AdminMinimum', boulderId: 'boulder-existing-1', type: 'top', createdAt: '2026-09-03T11:15:00Z' },
  { id: 'ascent-3', userId: 'admin-6aplus', userNickname: 'Admin6APlus', boulderId: 'boulder-existing-1', type: 'top', createdAt: '2026-09-03T18:45:00Z' },
  { id: 'ascent-4', userId: 'schrauber-6aplus', userNickname: 'Schrauber6aPlus', boulderId: 'boulder-existing-1', type: 'project', createdAt: '2026-09-04T10:00:00Z' },
  { id: 'ascent-hans-1', userId: 'hans-kletterer', userNickname: 'HansDereinfacheKletterer', boulderId: 'boulder-existing-1', type: 'top', createdAt: '2026-09-04T10:10:00Z' },
  { id: 'ascent-admin-min-1', userId: 'admin-minimum', userNickname: 'AdminMinimum', boulderId: 'boulder-existing-1', type: 'flash', createdAt: '2026-09-04T10:15:00Z' },
  { id: 'ascent-5', userId: 'schrauber-minimum', userNickname: 'Schrauber Minimum', boulderId: 'boulder-existing-2', type: 'top', createdAt: '2026-09-02T19:00:00Z' },
  { id: 'ascent-6', userId: 'hans-kletterer', userNickname: 'HansDereinfacheKletterer', boulderId: 'boulder-existing-2', type: 'flash', createdAt: '2026-09-04T14:20:00Z' },

  // Boris' Personal Ascents in Minimum
  { id: 'ascent-boris-1', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-existing-1', type: 'project', createdAt: '2026-09-04T17:00:00Z' },
  { id: 'ascent-boris-2', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-existing-2', type: 'flash', createdAt: '2026-09-04T17:15:00Z' },
  { id: 'ascent-boris-3', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-overhang-3', type: 'top', createdAt: '2026-09-04T17:30:00Z' },
  { id: 'ascent-boris-4', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-overhang-4', type: 'flash', createdAt: '2026-09-04T17:45:00Z' },
  { id: 'ascent-boris-5', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-overhang-5', type: 'flash', createdAt: '2026-09-04T18:00:00Z' },
  { id: 'ascent-boris-6', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-overhang-6', type: 'top', createdAt: '2026-09-04T18:20:00Z' },
  { id: 'ascent-boris-7', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-overhang-archived-1', type: 'top', createdAt: '2026-08-01T17:00:00Z' },
  { id: 'ascent-boris-8', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-slab-1', type: 'flash', createdAt: '2026-09-03T16:00:00Z' },
  { id: 'ascent-boris-9', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-slab-2', type: 'top', createdAt: '2026-09-03T16:20:00Z' },
  { id: 'ascent-boris-10', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-slab-3', type: 'project', createdAt: '2026-09-03T16:40:00Z' },
  { id: 'ascent-boris-11', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-slab-5', type: 'top', createdAt: '2026-09-03T17:00:00Z' },
  { id: 'ascent-boris-12', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-slab-6', type: 'flash', createdAt: '2026-09-03T17:20:00Z' },
  { id: 'ascent-boris-13', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-roof-1', type: 'top', createdAt: '2026-09-01T17:00:00Z' },
  { id: 'ascent-boris-14', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-roof-2', type: 'flash', createdAt: '2026-09-01T17:30:00Z' },
  { id: 'ascent-boris-15', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-roof-4', type: 'project', createdAt: '2026-09-01T18:00:00Z' },
  { id: 'ascent-boris-16', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-roof-5', type: 'flash', createdAt: '2026-09-01T18:30:00Z' },
];

// -------------------------------------------------------------
// Seed Ratings
// -------------------------------------------------------------
export const SEED_RATINGS: BoulderRating[] = [
  {
    id: 'rating-1',
    boulderId: 'boulder-existing-1',
    userId: 'hans-kletterer',
    userNickname: 'HansDereinfacheKletterer',
    gradeFeel: 'soft',
    qualityStars: 5,
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 3, balance: 2, koordination: 4, flexibilitaet: 2 },
    createdAt: '2026-09-02T16:35:00Z',
    updatedAt: '2026-09-02T16:35:00Z',
  },
  {
    id: 'rating-2',
    boulderId: 'boulder-existing-1',
    userId: 'admin-minimum',
    userNickname: 'AdminMinimum',
    gradeFeel: 'fair',
    qualityStars: 4,
    radar: { maximalkraft: 5, kraftausdauer: 3, kraft: 5, technik: 3, balance: 3, koordination: 4, flexibilitaet: 2 },
    createdAt: '2026-09-03T11:20:00Z',
    updatedAt: '2026-09-03T11:20:00Z',
  },
  {
    id: 'rating-3',
    boulderId: 'boulder-existing-1',
    userId: 'admin-6aplus',
    userNickname: 'Admin6APlus',
    gradeFeel: 'soft',
    qualityStars: 4,
    radar: { maximalkraft: 3, kraftausdauer: 3, kraft: 3, technik: 3, balance: 2, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-09-03T18:50:00Z',
    updatedAt: '2026-09-03T18:50:00Z',
  },
  {
    id: 'rating-4',
    boulderId: 'boulder-existing-2',
    userId: 'schrauber-minimum',
    userNickname: 'Schrauber Minimum',
    gradeFeel: 'stiff',
    qualityStars: 5,
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 5, balance: 4, koordination: 3, flexibilitaet: 4 },
    createdAt: '2026-09-02T19:05:00Z',
    updatedAt: '2026-09-02T19:05:00Z',
  },
];

// -------------------------------------------------------------
// Seed CRUD Boulders (Feature 1 Demo Data)
// -------------------------------------------------------------
export const SEED_CRUD_BOULDERS: BoulderInput[] = [
  {
    name: 'Rainbow Rocket',
    location: 'Fontainebleau',
    sector: 'Cuvier Rempart',
    date: '2026-09-02',
    gradeScale: 'font',
    grade: '8A',
    ascentStyle: 'top',
    attempts: 14,
    wallAngle: 'vertical',
    holdTypes: ['sloper', 'crimp'],
    perceivedDifficulty: 'fair',
    rating: 5,
    cruxDescription: 'Dynamischer Weitsprung von der Untergriff-Leiste auf die abgerundete Sloper-Kante. Volle Körperspannung beim Abfangen.',
    notes: 'Klassischer Weltklasse-Dyno. Perfektes Reibungswetter bei 12°C.',
    tags: ['dyno', 'highball', 'classic'],
  },
  {
    name: 'Karma',
    location: 'Fontainebleau',
    sector: 'Cuvier Rempart',
    date: '2026-09-02',
    gradeScale: 'font',
    grade: '7A+',
    ascentStyle: 'flash',
    attempts: 1,
    wallAngle: 'vertical',
    holdTypes: ['sloper', 'pinch'],
    perceivedDifficulty: 'soft',
    rating: 5,
    cruxDescription: 'Präziser Schulterzug und anschließender Mantle.',
    notes: 'Flash gelungen dank perfekter Beta von Jonas!',
    tags: ['sloper', 'mantle'],
  },
  {
    name: 'Dach-Projekt 42',
    location: 'Minimum Zürich',
    sector: 'Wettkampf-Dach',
    date: '2026-09-04',
    gradeScale: 'font',
    grade: '7C',
    ascentStyle: 'project',
    attempts: 7,
    wallAngle: 'roof',
    holdTypes: ['pinch', 'crimp', 'volume'],
    perceivedDifficulty: 'hard',
    rating: 4,
    cruxDescription: 'Toe-Hook halten während weitem Zug auf die linke Zange. Beim Hook-Release nicht von der Wand abreißen.',
    notes: 'Sequenz bis Zug 5 steht stabil. Nächstes Mal Ausstieg probieren.',
    tags: ['roof', 'toehook', 'project'],
  },
];
