import {
  Gym,
  GymGradeScale,
  Sector,
  WallBoulder,
  Ascent,
  BoulderRating,
  UserProfile,
  BoulderInput,
} from '../types/boulder';

// -------------------------------------------------------------
// Seed Gym, Scales & Sectors (Minimum Boulder Zürich)
// -------------------------------------------------------------
export const SEED_GYM: Gym = {
  id: 'gym-minimum-zh',
  name: 'Minimum Boulder Zürich',
  city: 'Zürich',
  address: 'Flüelastrasse 31, 8048 Zürich',
  createdBy: 'user-admin-1',
  createdAt: '2026-09-01T10:00:00Z',
};

export const SEED_6A_PLUS_GRADE_SCALES: GymGradeScale[] = [
  { id: '6f66405a-0cdc-4bfa-9f27-4f60cb2517bf', gymId: 'gym-6a-plus', colorName: 'Sonnengelb', colorHex: '#fde047', difficultyLabel: 'Anfaenger Plus', fontRangeMin: '3', fontRangeMax: '4+', sortOrder: 1 },
  { id: 'b65dc31e-21e5-4612-a0cc-2b60891c78de', gymId: 'gym-6a-plus', colorName: 'Blau', colorHex: '#3b82f6', difficultyLabel: 'Gemütlich', fontRangeMin: '3', fontRangeMax: '4+', sortOrder: 2 },
  { id: '6d5f72b1-6e4d-45e8-8a9f-bd5cb60222b9', gymId: 'gym-6a-plus', colorName: 'Grün', colorHex: '#22c55e', difficultyLabel: 'Flott', fontRangeMin: '5', fontRangeMax: '5+', sortOrder: 3 },
  { id: 'fce60743-1a3a-4122-9b60-bd91cbb56abd', gymId: 'gym-6a-plus', colorName: 'Gelb', colorHex: '#eab308', difficultyLabel: 'Trick', fontRangeMin: '6a', fontRangeMax: '6b', sortOrder: 4 },
  { id: 'f7bdc2a9-7af8-47f0-b144-67f1fbcd8dc1', gymId: 'gym-6a-plus', colorName: 'Rot', colorHex: '#ef4444', difficultyLabel: 'Rassig', fontRangeMin: '6b+', fontRangeMax: '6c+', sortOrder: 5 },
  { id: '3e322450-4c56-4422-8c88-7f518b716352', gymId: 'gym-6a-plus', colorName: 'Weiss', colorHex: '#f8fafc', difficultyLabel: 'Böse', fontRangeMin: '7a', fontRangeMax: '7b', sortOrder: 6 },
  { id: 'b61e5d67-e55e-4c34-a577-34e8370bd863', gymId: 'gym-6a-plus', colorName: 'Schwarz', colorHex: '#1e293b', difficultyLabel: 'Sehr schwer', fontRangeMin: '7B', fontRangeMax: '7C+', sortOrder: 7 },
  { id: '85acace1-378a-48d9-958b-0ab2a2510db2', gymId: 'gym-6a-plus', colorName: 'Beige', colorHex: '#d2b48c', difficultyLabel: 'Bestial', fontRangeMin: '7b+', fontRangeMax: '8c+', sortOrder: 8 },
];

export const SEED_GRADE_SCALES: GymGradeScale[] = [
  { id: 'f94c7727-5096-4d9f-bcd6-63bd55ae1fbd', gymId: 'gym-minimum-zh', colorName: 'Grün', colorHex: '#22c55e', difficultyLabel: 'Leicht', fontRangeMin: '4a', fontRangeMax: '5b', sortOrder: 1 },
  { id: 'b1b5f951-bc31-468f-802d-5f63ab651222', gymId: 'gym-minimum-zh', colorName: 'Blau', colorHex: '#3b82f6', difficultyLabel: 'Fortgeschritten', fontRangeMin: '5c', fontRangeMax: '6b', sortOrder: 2 },
  { id: '6b538536-2fe3-4c97-a5ab-16df8ac19ad3', gymId: 'gym-minimum-zh', colorName: 'Gelb', colorHex: '#eab308', difficultyLabel: 'Sportlich', fontRangeMin: '6b+', fontRangeMax: '7a', sortOrder: 3 },
  { id: '130c2372-d28e-416c-85af-a3380426c9bd', gymId: 'gym-minimum-zh', colorName: 'Rot', colorHex: '#ef4444', difficultyLabel: 'Schwer', fontRangeMin: '7a+', fontRangeMax: '7b+', sortOrder: 4 },
  { id: '2ccf3d7f-a886-4a8e-9bad-25771edf9e86', gymId: 'gym-minimum-zh', colorName: 'Schwarz', colorHex: '#1e293b', difficultyLabel: 'Sehr schwer', fontRangeMin: '7c', fontRangeMax: '8a', sortOrder: 5 },
  { id: '2dfafa3a-f172-4ee0-ae0c-fddc2a23a851', gymId: 'gym-minimum-zh', colorName: 'Weiß', colorHex: '#f8fafc', difficultyLabel: 'Elite', fontRangeMin: '8a+', fontRangeMax: '8b+', sortOrder: 6 },
  { id: 'eb803c73-40cb-4108-a4cc-d299acc7c44a', gymId: 'gym-minimum-zh', colorName: 'Tuerkis', colorHex: '#14b8a6', difficultyLabel: 'Spezial', fontRangeMin: '6B', fontRangeMax: '6C', sortOrder: 7 },
  { id: '3c7ab2bc-a337-4ba3-afb2-4005f245b56c', gymId: 'gym-minimum-zh', colorName: 'Pink', colorHex: '#ec4899', difficultyLabel: 'Projekt-Crux', fontRangeMin: '7B', fontRangeMax: '8A', sortOrder: 8 },
  ...SEED_6A_PLUS_GRADE_SCALES
];

export const SEED_6A_PLUS_SECTORS: Sector[] = [
  { id: 'sec_6a_slab_vorne', gymId: 'gym-6a-plus', name: 'Slab Vorne', wallPhotoUrl: '/images/walls/6aplus/SlapVorne.jpg', sortOrder: 1, createdAt: '2026-09-01T10:00:00Z' },
  { id: 'sec_6a_ecke_vorne', gymId: 'gym-6a-plus', name: 'Ecke Vorne', wallPhotoUrl: '/images/walls/6aplus/EckeVorne.jpg', sortOrder: 2, createdAt: '2026-09-01T10:00:00Z' },
  { id: 'sec_6a_zwischenwand_vorne', gymId: 'gym-6a-plus', name: 'Zwischenwand Vorne', wallPhotoUrl: '/images/walls/6aplus/ZwischenwandVorne.jpg', sortOrder: 3, createdAt: '2026-09-01T10:00:00Z' },
  { id: 'sec_6a_ueberhang_vorne', gymId: 'gym-6a-plus', name: 'Überhang Vorne', wallPhotoUrl: '/images/walls/6aplus/UerberhangVorne.jpg', sortOrder: 4, createdAt: '2026-09-01T10:00:00Z' },
  { id: 'sec_6a_verlaengerung_ueberhang', gymId: 'gym-6a-plus', name: 'Verlängerung Überhang', wallPhotoUrl: '/images/walls/6aplus/VerlaengerungUeberhang.jpg', sortOrder: 5, createdAt: '2026-09-01T10:00:00Z' },
  { id: 'sec_6a_ecke_mitte', gymId: 'gym-6a-plus', name: 'Ecke Mitte', wallPhotoUrl: '/images/walls/6aplus/EckeMitte.jpg', sortOrder: 6, createdAt: '2026-09-01T10:00:00Z' },
  { id: 'sec_6a_cave', gymId: 'gym-6a-plus', name: 'Cave', wallPhotoUrl: '/images/walls/6aplus/Cave.jpg', sortOrder: 7, createdAt: '2026-09-01T10:00:00Z' },
  { id: 'sec_6a_cave_wand', gymId: 'gym-6a-plus', name: 'Cave Wand', wallPhotoUrl: '/images/walls/6aplus/CaveWand.jpg', sortOrder: 8, createdAt: '2026-09-01T10:00:00Z' },
];

export const SEED_SECTORS: Sector[] = [
  ...SEED_6A_PLUS_SECTORS,
  {
    id: 'sector-overhang',
    gymId: 'gym-minimum-zh',
    name: 'Überhang 45°',
    wallPhotoUrl: '/images/walls/overhang.jpg',
    sortOrder: 1,
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'sector-slab',
    gymId: 'gym-minimum-zh',
    name: 'Platte (Slab & Balance)',
    wallPhotoUrl: '/images/walls/slab.jpg',
    sortOrder: 2,
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'sector-roof',
    gymId: 'gym-minimum-zh',
    name: 'Wettkampf-Dach & Cave',
    wallPhotoUrl: '/images/walls/roof.jpg',
    sortOrder: 3,
    createdAt: '2026-09-01T10:00:00Z',
  },
];

// -------------------------------------------------------------
// Seed Wall Boulders (6a plus & Minimum Zürich)
// -------------------------------------------------------------
export const SEED_6A_BOULDERS: WallBoulder[] = [
  // --- 6a plus Sector: Überhang Vorne ---
  {
    id: 'boulder-6a-ueberhang-onemove',
    sectorId: 'sec_6a_ueberhang_vorne',
    gradeScaleId: 'scale_6a_blau',
    positionX: 0.35,
    positionY: 0.45,
    name: 'OneMoveBoulder',
    notes: 'Ein kräftiger dynamischer Schlüsselzug zur Zange',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 4, balance: 3, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-09-05T10:00:00Z',
    publishedAt: '2026-09-05T12:00:00Z',
  },
  {
    id: 'boulder-6a-ueberhang-hartesding',
    sectorId: 'sec_6a_ueberhang_vorne',
    gradeScaleId: 'scale_6a_beige',
    positionX: 0.65,
    positionY: 0.35,
    name: 'hartes Ding',
    notes: 'Komplexe Crux auf Mikroleisten im Überhang',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 4, kraft: 5, technik: 5, balance: 2, koordination: 3, flexibilitaet: 4 },
    createdAt: '2026-09-05T10:30:00Z',
    publishedAt: '2026-09-05T12:00:00Z',
  },
  {
    id: 'boulder-6a-ueberhang-weiss',
    sectorId: 'sec_6a_ueberhang_vorne',
    gradeScaleId: 'scale_6a_weiss',
    positionX: 0.50,
    positionY: 0.25,
    name: 'Weiss',
    notes: 'Extrem schweres Dachausstiegs-Problem',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 5, kraft: 5, technik: 5, balance: 3, koordination: 4, flexibilitaet: 4 },
    createdAt: '2026-09-05T11:00:00Z',
    publishedAt: '2026-09-05T12:00:00Z',
  },
  {
    id: 'boulder-6a-ueberhang-blau',
    sectorId: 'sec_6a_ueberhang_vorne',
    gradeScaleId: 'scale_6a_blau',
    positionX: 0.40,
    positionY: 0.55,
    name: 'Blau',
    notes: 'Solide Linie mit weiten Zügen an guten Henkeln',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 3, kraft: 3, technik: 4, balance: 3, koordination: 3, flexibilitaet: 3 },
    createdAt: '2026-09-05T11:15:00Z',
    publishedAt: '2026-09-05T12:00:00Z',
  },
  {
    id: 'boulder-6a-ueberhang-gruen',
    sectorId: 'sec_6a_ueberhang_vorne',
    gradeScaleId: 'scale_6a_gruen',
    positionX: 0.25,
    positionY: 0.65,
    name: 'Grün',
    notes: 'Einstiegsroute im vorderen Überhang',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 2, kraft: 2, technik: 3, balance: 3, koordination: 2, flexibilitaet: 2 },
    createdAt: '2026-09-05T11:30:00Z',
    publishedAt: '2026-09-05T12:00:00Z',
  },
  {
    id: 'boulder-6a-ueberhang-rot',
    sectorId: 'sec_6a_ueberhang_vorne',
    gradeScaleId: 'scale_6a_rot',
    positionX: 0.72,
    positionY: 0.48,
    name: 'Rot',
    notes: 'Heelhook und weite Schulterzüge an Slopern',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 4, kraft: 4, technik: 4, balance: 3, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-09-05T11:45:00Z',
    publishedAt: '2026-09-05T12:00:00Z',
  },
  {
    id: '4d3b335c-5125-46d9-b0b8-9b8748dd879c',
    sectorId: 'sec_6a_ueberhang_vorne',
    gradeScaleId: 'scale_6a_blau',
    positionX: 0.52,
    positionY: 0.38,
    name: '6a+ Überhang-Crux',
    notes: 'Der Klassiker im Überhang Vorne',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 4, balance: 3, koordination: 3, flexibilitaet: 3 },
    createdAt: '2026-09-01T10:00:00Z',
    publishedAt: '2026-09-01T12:00:00Z',
  },
  {
    id: 'boulder-6a-ueberhang-gelb',
    sectorId: 'sec_6a_ueberhang_vorne',
    gradeScaleId: 'scale_6a_gelb',
    positionX: 0.18,
    positionY: 0.72,
    name: 'Gelber Dynamo',
    notes: 'Leichte Einstiegstour mit großen Griffen',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 2, kraft: 2, technik: 2, balance: 3, koordination: 2, flexibilitaet: 2 },
    createdAt: '2026-09-05T12:00:00Z',
    publishedAt: '2026-09-05T12:00:00Z',
  },

  // --- 6a plus Sector: Slab Vorne ---
  {
    id: 'a06a9337-4e3d-4b78-8dcf-aa697418a836',
    sectorId: 'sec_6a_slab_vorne',
    gradeScaleId: 'scale_6a_gelb',
    positionX: 0.32,
    positionY: 0.62,
    name: 'Gelber Auftakt',
    notes: 'Schöne Reibungsplatte für Einsteiger',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 1, kraftausdauer: 2, kraft: 1, technik: 3, balance: 4, koordination: 2, flexibilitaet: 3 },
    createdAt: '2026-09-01T10:00:00Z',
    publishedAt: '2026-09-01T12:00:00Z',
  },
  {
    id: 'boulder-6a-slab-2',
    sectorId: 'sec_6a_slab_vorne',
    gradeScaleId: 'scale_6a_gruen',
    positionX: 0.48,
    positionY: 0.50,
    name: 'Reibungs-Kante',
    notes: 'Präzises Antreten auf Mikrotropfen',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 2, kraft: 2, technik: 4, balance: 5, koordination: 3, flexibilitaet: 4 },
    createdAt: '2026-09-02T10:00:00Z',
    publishedAt: '2026-09-02T12:00:00Z',
  },
  {
    id: 'boulder-6a-slab-3',
    sectorId: 'sec_6a_slab_vorne',
    gradeScaleId: 'scale_6a_blau',
    positionX: 0.68,
    positionY: 0.40,
    name: 'Balance-Pfeiler',
    notes: 'Körperschwerpunkt halten und auf Reibung vertrauen',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 3, kraft: 2, technik: 5, balance: 5, koordination: 4, flexibilitaet: 4 },
    createdAt: '2026-09-02T10:30:00Z',
    publishedAt: '2026-09-02T12:00:00Z',
  },
  {
    id: 'boulder-6a-slab-4',
    sectorId: 'sec_6a_slab_vorne',
    gradeScaleId: 'scale_6a_rot',
    positionX: 0.24,
    positionY: 0.34,
    name: 'Mikro-Sloper',
    notes: 'Extrem flache Griffe, viel Druck auf die Füße',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 3, kraft: 3, technik: 5, balance: 5, koordination: 3, flexibilitaet: 4 },
    createdAt: '2026-09-02T11:00:00Z',
    publishedAt: '2026-09-02T12:00:00Z',
  },
  {
    id: 'boulder-6a-slab-5',
    sectorId: 'sec_6a_slab_vorne',
    gradeScaleId: 'scale_6a_beige',
    positionX: 0.55,
    positionY: 0.25,
    name: 'Glatteis',
    notes: 'Nur für mutige Plattenliebhaber',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 3, kraft: 3, technik: 5, balance: 5, koordination: 4, flexibilitaet: 5 },
    createdAt: '2026-09-02T11:30:00Z',
    publishedAt: '2026-09-02T12:00:00Z',
  },

  // --- 6a plus Sector: Ecke Vorne ---
  {
    id: 'f846dd8c-6cee-4583-b91c-d9e3cc65d11a',
    sectorId: 'sec_6a_ecke_vorne',
    gradeScaleId: 'scale_6a_gruen',
    positionX: 0.30,
    positionY: 0.58,
    name: 'Ecken-Schleicher',
    notes: 'Elegante Verschneidungstechnik',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 2, kraft: 2, technik: 4, balance: 4, koordination: 3, flexibilitaet: 3 },
    createdAt: '2026-09-01T10:00:00Z',
    publishedAt: '2026-09-01T12:00:00Z',
  },
  {
    id: 'boulder-6a-ecke-2',
    sectorId: 'sec_6a_ecke_vorne',
    gradeScaleId: 'scale_6a_blau',
    positionX: 0.52,
    positionY: 0.45,
    name: 'Verschneidungs-Tanz',
    notes: 'Stemmen und Gegendruck in der Kante',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 3, kraft: 3, technik: 4, balance: 4, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-09-03T10:00:00Z',
    publishedAt: '2026-09-03T12:00:00Z',
  },
  {
    id: 'boulder-6a-ecke-3',
    sectorId: 'sec_6a_ecke_vorne',
    gradeScaleId: 'scale_6a_rot',
    positionX: 0.70,
    positionY: 0.35,
    name: 'Kanten-Druck',
    notes: 'Weite Züge um die Kante herum',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 4, kraft: 4, technik: 4, balance: 3, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-09-03T10:30:00Z',
    publishedAt: '2026-09-03T12:00:00Z',
  },
  {
    id: 'boulder-6a-ecke-4',
    sectorId: 'sec_6a_ecke_vorne',
    gradeScaleId: 'scale_6a_gelb',
    positionX: 0.20,
    positionY: 0.70,
    name: 'Gelbe Verschneidung',
    notes: 'Leichter Einstieg mit stabilen Griffen',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 2, kraft: 2, technik: 3, balance: 3, koordination: 2, flexibilitaet: 2 },
    createdAt: '2026-09-03T11:00:00Z',
    publishedAt: '2026-09-03T12:00:00Z',
  },

  // --- 6a plus Sector: Zwischenwand Vorne ---
  {
    id: '26e01df6-f5a2-48e5-adeb-d0eb05c02531',
    sectorId: 'sec_6a_zwischenwand_vorne',
    gradeScaleId: 'scale_6a_blau',
    positionX: 0.38,
    positionY: 0.52,
    name: '6A+ Zwischenwand-Traverse',
    notes: 'Technisch anspruchsvolle Traverse',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 4, kraft: 3, technik: 4, balance: 4, koordination: 3, flexibilitaet: 3 },
    createdAt: '2026-09-01T10:00:00Z',
    publishedAt: '2026-09-01T12:00:00Z',
  },
  {
    id: 'boulder-6a-zw-2',
    sectorId: 'sec_6a_zwischenwand_vorne',
    gradeScaleId: 'scale_6a_rot',
    positionX: 0.58,
    positionY: 0.38,
    name: 'Wand-Direkt',
    notes: 'Kleine Leisten gerade nach oben',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 4, balance: 3, koordination: 3, flexibilitaet: 3 },
    createdAt: '2026-09-03T14:00:00Z',
    publishedAt: '2026-09-03T16:00:00Z',
  },
  {
    id: 'boulder-6a-zw-3',
    sectorId: 'sec_6a_zwischenwand_vorne',
    gradeScaleId: 'scale_6a_gruen',
    positionX: 0.25,
    positionY: 0.65,
    name: 'Dyno-Move',
    notes: 'Dynamischer Zug an die große Schuppe',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 2, kraft: 3, technik: 3, balance: 3, koordination: 4, flexibilitaet: 2 },
    createdAt: '2026-09-03T14:30:00Z',
    publishedAt: '2026-09-03T16:00:00Z',
  },
  {
    id: 'boulder-6a-zw-4',
    sectorId: 'sec_6a_zwischenwand_vorne',
    gradeScaleId: 'scale_6a_beige',
    positionX: 0.72,
    positionY: 0.30,
    name: 'Crimp Master',
    notes: 'Knackige Fingerkraft-Crux',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 4, kraft: 5, technik: 5, balance: 2, koordination: 3, flexibilitaet: 3 },
    createdAt: '2026-09-03T15:00:00Z',
    publishedAt: '2026-09-03T16:00:00Z',
  },

  // --- 6a plus Sector: Verlängerung Überhang ---
  {
    id: 'boulder-6a-verl-1',
    sectorId: 'sec_6a_verlaengerung_ueberhang',
    gradeScaleId: 'scale_6a_rot',
    positionX: 0.35,
    positionY: 0.50,
    name: 'Ausdauer-Monster',
    notes: 'Lange Route durch den fortlaufenden Überhang',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 5, kraft: 4, technik: 4, balance: 3, koordination: 3, flexibilitaet: 3 },
    createdAt: '2026-09-04T10:00:00Z',
    publishedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 'boulder-6a-verl-2',
    sectorId: 'sec_6a_verlaengerung_ueberhang',
    gradeScaleId: 'scale_6a_blau',
    positionX: 0.55,
    positionY: 0.42,
    name: 'Volumen-Hüpfer',
    notes: 'Große Züge über zwei Dreiecks-Volumen',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 4, kraft: 3, technik: 3, balance: 3, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-09-04T10:30:00Z',
    publishedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 'boulder-6a-verl-3',
    sectorId: 'sec_6a_verlaengerung_ueberhang',
    gradeScaleId: 'scale_6a_beige',
    positionX: 0.70,
    positionY: 0.32,
    name: 'Schulterzug',
    notes: 'Weiter Gastongriff und Heel-Hook-Stabilisierung',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 4, kraft: 5, technik: 4, balance: 3, koordination: 4, flexibilitaet: 4 },
    createdAt: '2026-09-04T11:00:00Z',
    publishedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 'boulder-6a-verl-4',
    sectorId: 'sec_6a_verlaengerung_ueberhang',
    gradeScaleId: 'scale_6a_gelb',
    positionX: 0.20,
    positionY: 0.68,
    name: 'Gelbe Ausdauer',
    notes: 'Schöne Warmup-Route im Überhang',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 3, kraft: 2, technik: 2, balance: 2, koordination: 2, flexibilitaet: 2 },
    createdAt: '2026-09-04T11:30:00Z',
    publishedAt: '2026-09-04T12:00:00Z',
  },

  // --- 6a plus Sector: Ecke Mitte ---
  {
    id: 'boulder-6a-eckm-1',
    sectorId: 'sec_6a_ecke_mitte',
    gradeScaleId: 'scale_6a_blau',
    positionX: 0.34,
    positionY: 0.48,
    name: 'Kompression',
    notes: 'Kompression an beiden Wandseiten',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 4, balance: 3, koordination: 3, flexibilitaet: 3 },
    createdAt: '2026-09-04T14:00:00Z',
    publishedAt: '2026-09-04T16:00:00Z',
  },
  {
    id: 'boulder-6a-eckm-2',
    sectorId: 'sec_6a_ecke_mitte',
    gradeScaleId: 'scale_6a_rot',
    positionX: 0.62,
    positionY: 0.36,
    name: 'Pfeiler-Schlitz',
    notes: 'Untergriff und Hook an der Pfeilerkante',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 4, kraft: 4, technik: 4, balance: 3, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-09-04T14:30:00Z',
    publishedAt: '2026-09-04T16:00:00Z',
  },
  {
    id: 'boulder-6a-eckm-3',
    sectorId: 'sec_6a_ecke_mitte',
    gradeScaleId: 'scale_6a_beige',
    positionX: 0.50,
    positionY: 0.26,
    name: 'Heel-Hook-Wunder',
    notes: 'Entlastung durch extremen Heelhook nötig',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 3, kraft: 5, technik: 5, balance: 3, koordination: 3, flexibilitaet: 4 },
    createdAt: '2026-09-04T15:00:00Z',
    publishedAt: '2026-09-04T16:00:00Z',
  },
  {
    id: 'boulder-6a-eckm-4',
    sectorId: 'sec_6a_ecke_mitte',
    gradeScaleId: 'scale_6a_gelb',
    positionX: 0.22,
    positionY: 0.65,
    name: 'Eck-Einstieg',
    notes: 'Klassische Kletterei zum Aufwärmen',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 2, kraft: 2, technik: 2, balance: 3, koordination: 2, flexibilitaet: 2 },
    createdAt: '2026-09-04T15:30:00Z',
    publishedAt: '2026-09-04T16:00:00Z',
  },

  // --- 6a plus Sector: Cave ---
  {
    id: '6f1ff2c6-67c2-41a8-8b65-7cc3c2e1f6a8',
    sectorId: 'sec_6a_cave',
    gradeScaleId: 'scale_6a_rot',
    positionX: 0.65,
    positionY: 0.45,
    name: 'Cave Power Rot',
    notes: 'Dach-Kletterei mit vollem Körpereinsatz',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 4, kraft: 5, technik: 4, balance: 2, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-09-01T10:00:00Z',
    publishedAt: '2026-09-01T12:00:00Z',
  },
  {
    id: 'boulder-6a-cave-2',
    sectorId: 'sec_6a_cave',
    gradeScaleId: 'scale_6a_blau',
    positionX: 0.42,
    positionY: 0.58,
    name: 'Dach-Kante',
    notes: 'Flacher Einstieg und Ausstieg über die Dachkante',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 4, balance: 3, koordination: 3, flexibilitaet: 3 },
    createdAt: '2026-09-05T09:00:00Z',
    publishedAt: '2026-09-05T11:00:00Z',
  },
  {
    id: 'boulder-6a-cave-3',
    sectorId: 'sec_6a_cave',
    gradeScaleId: 'scale_6a_beige',
    positionX: 0.55,
    positionY: 0.30,
    name: 'Ausstiegs-Dynamik',
    notes: 'Schwerer Dynamo beim Verlassen des Dachs',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 4, kraft: 5, technik: 4, balance: 2, koordination: 5, flexibilitaet: 3 },
    createdAt: '2026-09-05T09:30:00Z',
    publishedAt: '2026-09-05T11:00:00Z',
  },
  {
    id: 'boulder-6a-cave-4',
    sectorId: 'sec_6a_cave',
    gradeScaleId: 'scale_6a_gelb',
    positionX: 0.25,
    positionY: 0.72,
    name: 'Grotte Gelb',
    notes: 'Sehr griffige Schuppen im Einstiegsbereich',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 2, kraft: 2, technik: 2, balance: 2, koordination: 2, flexibilitaet: 2 },
    createdAt: '2026-09-05T10:00:00Z',
    publishedAt: '2026-09-05T11:00:00Z',
  },
  {
    id: 'boulder-6a-cave-5',
    sectorId: 'sec_6a_cave',
    gradeScaleId: 'scale_6a_weiss',
    positionX: 0.70,
    positionY: 0.22,
    name: 'The Beast',
    notes: 'Elite-Linie horizontal durchs Dach',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 5, kraft: 5, technik: 5, balance: 2, koordination: 4, flexibilitaet: 4 },
    createdAt: '2026-09-05T10:30:00Z',
    publishedAt: '2026-09-05T11:00:00Z',
  },

  // --- 6a plus Sector: Cave Wand ---
  {
    id: 'boulder-6a-cw-1',
    sectorId: 'sec_6a_cave_wand',
    gradeScaleId: 'scale_6a_rot',
    positionX: 0.38,
    positionY: 0.50,
    name: 'Höhlen-Leiste',
    notes: 'Kleine Leisten am Wandübergang',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 4, kraft: 4, technik: 4, balance: 3, koordination: 3, flexibilitaet: 3 },
    createdAt: '2026-09-05T13:00:00Z',
    publishedAt: '2026-09-05T15:00:00Z',
  },
  {
    id: 'boulder-6a-cw-2',
    sectorId: 'sec_6a_cave_wand',
    gradeScaleId: 'scale_6a_beige',
    positionX: 0.60,
    positionY: 0.35,
    name: 'Decken-Crux',
    notes: 'Maximale Körperspannung gefordert',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 4, kraft: 5, technik: 4, balance: 3, koordination: 3, flexibilitaet: 4 },
    createdAt: '2026-09-05T13:30:00Z',
    publishedAt: '2026-09-05T15:00:00Z',
  },
  {
    id: 'boulder-6a-cw-3',
    sectorId: 'sec_6a_cave_wand',
    gradeScaleId: 'scale_6a_gruen',
    positionX: 0.20,
    positionY: 0.65,
    name: 'Wand-Warmup',
    notes: 'Gute Tritte und positive Henkel',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 2, kraft: 2, technik: 3, balance: 3, koordination: 2, flexibilitaet: 2 },
    createdAt: '2026-09-05T14:00:00Z',
    publishedAt: '2026-09-05T15:00:00Z',
  },
  {
    id: 'boulder-6a-cw-4',
    sectorId: 'sec_6a_cave_wand',
    gradeScaleId: 'scale_6a_blau',
    positionX: 0.72,
    positionY: 0.45,
    name: 'Blaues Dach',
    notes: 'Flüssige Bewegungen im Überhang',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 3, kraft: 3, technik: 4, balance: 3, koordination: 3, flexibilitaet: 3 },
    createdAt: '2026-09-05T14:30:00Z',
    publishedAt: '2026-09-05T15:00:00Z',
  },
  {
    id: 'boulder-6a-cw-5',
    sectorId: 'sec_6a_cave_wand',
    gradeScaleId: 'scale_6a_gelb',
    positionX: 0.48,
    positionY: 0.70,
    name: 'Gelbe Grotte',
    notes: 'Freundlicher Einstieg mit schönen Griffen',
    setterId: 'schrauber-6aplus',
    status: 'active',
    radar: { maximalkraft: 1, kraftausdauer: 2, kraft: 1, technik: 2, balance: 3, koordination: 2, flexibilitaet: 2 },
    createdAt: '2026-09-05T15:00:00Z',
    publishedAt: '2026-09-05T15:00:00Z',
  },
];

export const SEED_EXISTING_BOULDERS: WallBoulder[] = [
  ...SEED_6A_BOULDERS,
  // --- Sector 1: Überhang 45° ---
  {
    id: 'boulder-existing-1',
    sectorId: 'sector-overhang',
    gradeScaleId: 'scale-blue',
    positionX: 0.35,
    positionY: 0.42,
    name: 'Dyno King',
    notes: 'Dynamischer Sprung an die Leiste',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 3, balance: 2, koordination: 4, flexibilitaet: 2 },
    createdAt: '2026-08-25T14:00:00Z',
    publishedAt: '2026-08-25T18:00:00Z',
  },
  {
    id: 'boulder-existing-2',
    sectorId: 'sector-overhang',
    gradeScaleId: 'scale-yellow',
    positionX: 0.68,
    positionY: 0.55,
    name: 'Heel-Hook Madness',
    notes: 'Körperspannung am Untergriff',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 3, kraft: 3, technik: 5, balance: 4, koordination: 3, flexibilitaet: 4 },
    createdAt: '2026-08-25T14:30:00Z',
    publishedAt: '2026-08-25T18:00:00Z',
  },
  {
    id: 'boulder-overhang-3',
    sectorId: 'sector-overhang',
    gradeScaleId: 'scale-red',
    positionX: 0.22,
    positionY: 0.30,
    name: 'Power-Leiste',
    notes: 'Kleine Leisten im 45° Überhang',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 3, kraft: 5, technik: 4, balance: 2, koordination: 2, flexibilitaet: 3 },
    createdAt: '2026-08-26T10:00:00Z',
    publishedAt: '2026-08-26T14:00:00Z',
  },
  {
    id: 'boulder-overhang-4',
    sectorId: 'sector-overhang',
    gradeScaleId: 'scale-blue',
    positionX: 0.80,
    positionY: 0.65,
    name: 'Zangengriff Traverse',
    notes: 'Winklige Pinches und weite Züge',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 3, balance: 3, koordination: 3, flexibilitaet: 2 },
    createdAt: '2026-08-27T11:00:00Z',
    publishedAt: '2026-08-27T15:00:00Z',
  },
  {
    id: 'boulder-overhang-5',
    sectorId: 'sector-overhang',
    gradeScaleId: 'scale-green',
    positionX: 0.50,
    positionY: 0.75,
    name: 'Blocker-Kante',
    notes: 'Große Henkel zum Warmklettern',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 3, kraft: 3, technik: 3, balance: 2, koordination: 2, flexibilitaet: 2 },
    createdAt: '2026-08-28T09:00:00Z',
    publishedAt: '2026-08-28T12:00:00Z',
  },
  {
    id: 'boulder-overhang-6',
    sectorId: 'sector-overhang',
    gradeScaleId: 'scale-red',
    positionX: 0.45,
    positionY: 0.20,
    name: 'Der Rote Bulle',
    notes: 'Maximalkraft-Züge ohne Rastposition',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 3, kraft: 5, technik: 4, balance: 2, koordination: 3, flexibilitaet: 2 },
    createdAt: '2026-08-28T10:30:00Z',
    publishedAt: '2026-08-28T13:30:00Z',
  },
  {
    id: 'boulder-overhang-archived-1',
    sectorId: 'sector-overhang',
    gradeScaleId: 'scale-yellow',
    positionX: 0.60,
    positionY: 0.40,
    name: 'Retro-Kante 2025',
    notes: 'Abgeschraubte Legende am Pfeiler',
    setterId: 'setter-1',
    status: 'archived',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 4, balance: 3, koordination: 2, flexibilitaet: 3 },
    createdAt: '2026-07-01T10:00:00Z',
    publishedAt: '2026-07-01T14:00:00Z',
    archivedAt: '2026-08-15T18:00:00Z',
  },

  // --- Sector 2: Platte (Slab & Balance) ---
  {
    id: 'boulder-slab-1',
    sectorId: 'sector-slab',
    gradeScaleId: 'scale-green',
    positionX: 0.25,
    positionY: 0.65,
    name: 'Reibungstraum',
    notes: 'Nur auf Reibung stehen',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 1, kraftausdauer: 3, kraft: 1, technik: 4, balance: 5, koordination: 2, flexibilitaet: 4 },
    createdAt: '2026-08-26T11:00:00Z',
    publishedAt: '2026-08-26T15:00:00Z',
  },
  {
    id: 'boulder-slab-2',
    sectorId: 'sector-slab',
    gradeScaleId: 'scale-blue',
    positionX: 0.45,
    positionY: 0.48,
    name: 'Messers Schneide',
    notes: 'Kleine Tritte, saubere Gewichtsverlagerung',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 3, kraft: 2, technik: 5, balance: 5, koordination: 3, flexibilitaet: 4 },
    createdAt: '2026-08-26T12:00:00Z',
    publishedAt: '2026-08-26T16:00:00Z',
  },
  {
    id: 'boulder-slab-3',
    sectorId: 'sector-slab',
    gradeScaleId: 'scale-yellow',
    positionX: 0.70,
    positionY: 0.38,
    name: 'Körperschwerpunkt',
    notes: 'Hoher Antritt und delikate Balance',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 3, kraft: 2, technik: 5, balance: 5, koordination: 3, flexibilitaet: 5 },
    createdAt: '2026-08-27T14:00:00Z',
    publishedAt: '2026-08-27T18:00:00Z',
  },
  {
    id: 'boulder-slab-4',
    sectorId: 'sector-slab',
    gradeScaleId: 'scale-red',
    positionX: 0.35,
    positionY: 0.28,
    name: 'Mikrotropfen',
    notes: 'Fast grifflos, nur Sloper-Volumen',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 3, kraft: 3, technik: 5, balance: 5, koordination: 4, flexibilitaet: 4 },
    createdAt: '2026-08-27T15:00:00Z',
    publishedAt: '2026-08-27T19:00:00Z',
  },
  {
    id: 'boulder-slab-5',
    sectorId: 'sector-slab',
    gradeScaleId: 'scale-blue',
    positionX: 0.58,
    positionY: 0.72,
    name: 'Zirkus-Stepper',
    notes: 'Koordination über drei Volumen',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 2, kraftausdauer: 3, kraft: 2, technik: 4, balance: 4, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-08-28T11:00:00Z',
    publishedAt: '2026-08-28T15:00:00Z',
  },
  {
    id: 'boulder-slab-6',
    sectorId: 'sector-slab',
    gradeScaleId: 'scale-green',
    positionX: 0.15,
    positionY: 0.80,
    name: 'Platten-Finesse',
    notes: 'Leichter Einstieg mit schöner Fußarbeit',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 1, kraftausdauer: 3, kraft: 1, technik: 3, balance: 4, koordination: 2, flexibilitaet: 3 },
    createdAt: '2026-08-29T09:30:00Z',
    publishedAt: '2026-08-29T13:00:00Z',
  },
  {
    id: 'boulder-slab-archived-1',
    sectorId: 'sector-slab',
    gradeScaleId: 'scale-yellow',
    positionX: 0.82,
    positionY: 0.30,
    name: 'Die Glatte Wand',
    notes: 'Ehemaliges Platten-Projekt',
    setterId: 'setter-1',
    status: 'archived',
    radar: { maximalkraft: 2, kraftausdauer: 3, kraft: 2, technik: 5, balance: 5, koordination: 3, flexibilitaet: 4 },
    createdAt: '2026-07-10T11:00:00Z',
    publishedAt: '2026-07-10T15:00:00Z',
    archivedAt: '2026-08-18T16:00:00Z',
  },

  // --- Sector 3: Wettkampf-Dach & Cave ---
  {
    id: 'boulder-roof-1',
    sectorId: 'sector-roof',
    gradeScaleId: 'scale-blue',
    positionX: 0.30,
    positionY: 0.70,
    name: 'Fledermaus-Hook',
    notes: 'Toe-Hook Entlastung im Dach',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 4, balance: 3, koordination: 3, flexibilitaet: 5 },
    createdAt: '2026-08-28T13:00:00Z',
    publishedAt: '2026-08-28T17:00:00Z',
  },
  {
    id: 'boulder-roof-2',
    sectorId: 'sector-roof',
    gradeScaleId: 'scale-yellow',
    positionX: 0.52,
    positionY: 0.55,
    name: 'Dach-Kompressor',
    notes: 'Gegendruck auf zwei große Sloper',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 3, kraft: 5, technik: 4, balance: 2, koordination: 3, flexibilitaet: 3 },
    createdAt: '2026-08-28T14:00:00Z',
    publishedAt: '2026-08-28T18:00:00Z',
  },
  {
    id: 'boulder-roof-3',
    sectorId: 'sector-roof',
    gradeScaleId: 'scale-red',
    positionX: 0.75,
    positionY: 0.42,
    name: 'Wettkampf-Sprung',
    notes: 'Dynamischer Paddle-Dyno zur Kante',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 3, balance: 2, koordination: 5, flexibilitaet: 3 },
    createdAt: '2026-08-29T10:00:00Z',
    publishedAt: '2026-08-29T14:00:00Z',
  },
  {
    id: 'boulder-roof-4',
    sectorId: 'sector-roof',
    gradeScaleId: 'scale-black',
    positionX: 0.40,
    positionY: 0.25,
    name: 'Cave Ausstiegs-Crux',
    notes: 'Extrem harter Heel-Hook Ausstieg',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 5, kraftausdauer: 3, kraft: 5, technik: 5, balance: 3, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-08-29T11:00:00Z',
    publishedAt: '2026-08-29T15:00:00Z',
  },
  {
    id: 'boulder-roof-5',
    sectorId: 'sector-roof',
    gradeScaleId: 'scale-blue',
    positionX: 0.65,
    positionY: 0.68,
    name: 'Körperspannung Pur',
    notes: 'Füße dürfen nicht abrutschen',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 3, balance: 2, koordination: 2, flexibilitaet: 3 },
    createdAt: '2026-08-30T09:00:00Z',
    publishedAt: '2026-08-30T13:00:00Z',
  },
  {
    id: 'boulder-roof-6',
    sectorId: 'sector-roof',
    gradeScaleId: 'scale-green',
    positionX: 0.20,
    positionY: 0.82,
    name: 'Dach-Einstieg',
    notes: 'Gute Griffe durch die Schräge',
    setterId: 'setter-1',
    status: 'active',
    radar: { maximalkraft: 3, kraftausdauer: 3, kraft: 3, technik: 3, balance: 2, koordination: 2, flexibilitaet: 2 },
    createdAt: '2026-08-30T10:00:00Z',
    publishedAt: '2026-08-30T14:00:00Z',
  },
  {
    id: 'boulder-roof-archived-1',
    sectorId: 'sector-roof',
    gradeScaleId: 'scale-yellow',
    positionX: 0.50,
    positionY: 0.40,
    name: 'Horizontale Hölle',
    notes: 'Klassiker der letzten Saison',
    setterId: 'setter-1',
    status: 'archived',
    radar: { maximalkraft: 5, kraftausdauer: 3, kraft: 5, technik: 4, balance: 2, koordination: 3, flexibilitaet: 3 },
    createdAt: '2026-07-15T12:00:00Z',
    publishedAt: '2026-07-15T16:00:00Z',
    archivedAt: '2026-08-20T17:00:00Z',
  },
];

// -------------------------------------------------------------
// Seed Profiles
// -------------------------------------------------------------
export const SEED_PROFILES: UserProfile[] = [
  { id: 'user-boris', nickname: 'Boris', createdAt: '2026-05-15T10:00:00Z' },
  { id: 'admin-6aplus', nickname: 'Admin6APlus', createdAt: '2026-05-15T10:00:00Z' },
  { id: 'schrauber-6aplus', nickname: 'Schrauber6aPlus', createdAt: '2026-05-15T10:00:00Z' },
  { id: 'hans-kletterer', nickname: 'HansDereinfacheKletterer', createdAt: '2026-05-15T10:00:00Z' },
  { id: 'admin-minimum', nickname: 'AdminMinimum', createdAt: '2026-05-15T10:00:00Z' },
  { id: 'schrauber-minimum', nickname: 'Schrauber Minimum', createdAt: '2026-05-15T10:00:00Z' },
];

// -------------------------------------------------------------
// Seed Ascents (Community & Boris's session logs)
// -------------------------------------------------------------
export const SEED_ASCENTS: Ascent[] = [
  { id: 'ascent-1', userId: 'hans-kletterer', userNickname: 'HansDereinfacheKletterer', boulderId: 'boulder-existing-1', type: 'flash', createdAt: '2026-09-02T16:30:00Z' },
  { id: 'ascent-2', userId: 'admin-minimum', userNickname: 'AdminMinimum', boulderId: 'boulder-existing-1', type: 'top', createdAt: '2026-09-03T11:15:00Z' },
  { id: 'ascent-3', userId: 'admin-6aplus', userNickname: 'Admin6APlus', boulderId: 'boulder-existing-1', type: 'top', createdAt: '2026-09-03T18:45:00Z' },
  { id: 'ascent-4', userId: 'schrauber-6aplus', userNickname: 'Schrauber6aPlus', boulderId: 'boulder-existing-1', type: 'project', createdAt: '2026-09-04T10:00:00Z' },
  { id: 'ascent-hans-1', userId: 'hans-kletterer', userNickname: 'HansDereinfacheKletterer', boulderId: 'boulder-existing-1', type: 'top', createdAt: '2026-09-04T10:10:00Z' },
  { id: 'ascent-admin-min-1', userId: 'admin-minimum', userNickname: 'AdminMinimum', boulderId: 'boulder-existing-1', type: 'flash', createdAt: '2026-09-04T10:15:00Z' },
  { id: 'ascent-5', userId: 'schrauber-minimum', userNickname: 'Schrauber Minimum', boulderId: 'boulder-existing-2', type: 'top', createdAt: '2026-09-02T19:00:00Z' },
  { id: 'ascent-6', userId: 'hans-kletterer', userNickname: 'HansDereinfacheKletterer', boulderId: 'boulder-existing-2', type: 'flash', createdAt: '2026-09-04T14:20:00Z' },

  // Boris' Personal Ascents in Minimum
  { id: 'ascent-boris-1', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-existing-1', type: 'project', createdAt: '2026-09-04T17:00:00Z' },
  { id: 'ascent-boris-2', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-existing-2', type: 'flash', createdAt: '2026-09-04T17:15:00Z' },
  { id: 'ascent-boris-3', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-overhang-3', type: 'top', createdAt: '2026-09-04T17:30:00Z' },
  { id: 'ascent-boris-4', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-overhang-4', type: 'flash', createdAt: '2026-09-04T17:45:00Z' },
  { id: 'ascent-boris-5', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-overhang-5', type: 'flash', createdAt: '2026-09-04T18:00:00Z' },
  { id: 'ascent-boris-6', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-overhang-6', type: 'top', createdAt: '2026-09-04T18:20:00Z' },
  { id: 'ascent-boris-7', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-overhang-archived-1', type: 'top', createdAt: '2026-08-01T17:00:00Z' },
  { id: 'ascent-boris-8', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-slab-1', type: 'flash', createdAt: '2026-09-03T16:00:00Z' },
  { id: 'ascent-boris-9', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-slab-2', type: 'top', createdAt: '2026-09-03T16:20:00Z' },
  { id: 'ascent-boris-10', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-slab-3', type: 'project', createdAt: '2026-09-03T16:40:00Z' },
  { id: 'ascent-boris-11', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-slab-5', type: 'top', createdAt: '2026-09-03T17:00:00Z' },
  { id: 'ascent-boris-12', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-slab-6', type: 'flash', createdAt: '2026-09-03T17:20:00Z' },
  { id: 'ascent-boris-13', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-roof-1', type: 'top', createdAt: '2026-09-01T17:00:00Z' },
  { id: 'ascent-boris-14', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-roof-2', type: 'flash', createdAt: '2026-09-01T17:30:00Z' },
  { id: 'ascent-boris-15', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-roof-4', type: 'project', createdAt: '2026-09-01T18:00:00Z' },
  { id: 'ascent-boris-16', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-roof-5', type: 'flash', createdAt: '2026-09-01T18:30:00Z' },
  // Boris' Personal Ascents in 6a Plus
  { id: 'ascent-boris-6a-1', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-6a-ueberhang-onemove', type: 'flash', createdAt: '2026-09-05T14:00:00Z' },
  { id: 'ascent-boris-6a-2', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-6a-ueberhang-hartesding', type: 'project', createdAt: '2026-09-05T14:15:00Z' },
  { id: 'ascent-boris-6a-3', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-6a-ueberhang-blau', type: 'flash', createdAt: '2026-09-05T14:30:00Z' },
  { id: 'ascent-boris-6a-4', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-6a-ueberhang-gruen', type: 'flash', createdAt: '2026-09-05T14:45:00Z' },
  { id: 'ascent-boris-6a-5', userId: 'user-boris', userNickname: 'Boris', boulderId: 'boulder-6a-ueberhang-rot', type: 'top', createdAt: '2026-09-05T15:00:00Z' },
  { id: 'ascent-boris-6a-6', userId: 'user-boris', userNickname: 'Boris', boulderId: '4d3b335c-5125-46d9-b0b8-9b8748dd879c', type: 'top', createdAt: '2026-09-05T15:20:00Z' },
  { id: 'ascent-boris-6a-7', userId: 'user-boris', userNickname: 'Boris', boulderId: 'a06a9337-4e3d-4b78-8dcf-aa697418a836', type: 'flash', createdAt: '2026-09-05T15:40:00Z' },
  { id: 'ascent-boris-6a-8', userId: 'user-boris', userNickname: 'Boris', boulderId: '6f1ff2c6-67c2-41a8-8b65-7cc3c2e1f6a8', type: 'top', createdAt: '2026-09-05T16:00:00Z' },

  // Hans' Ascents in 6a Plus
  { id: 'ascent-hans-6a-1', userId: 'hans-kletterer', userNickname: 'HansDereinfacheKletterer', boulderId: 'boulder-6a-ueberhang-onemove', type: 'top', createdAt: '2026-09-05T16:30:00Z' },
  { id: 'ascent-hans-6a-2', userId: 'hans-kletterer', userNickname: 'HansDereinfacheKletterer', boulderId: 'boulder-6a-ueberhang-gruen', type: 'flash', createdAt: '2026-09-05T16:45:00Z' },
  { id: 'ascent-hans-6a-3', userId: 'hans-kletterer', userNickname: 'HansDereinfacheKletterer', boulderId: 'a06a9337-4e3d-4b78-8dcf-aa697418a836', type: 'top', createdAt: '2026-09-05T17:00:00Z' },
];

// -------------------------------------------------------------
// Seed Ratings
// -------------------------------------------------------------
export const SEED_RATINGS: BoulderRating[] = [
  {
    id: 'rating-1',
    boulderId: 'boulder-existing-1',
    userId: 'hans-kletterer',
    userNickname: 'HansDereinfacheKletterer',
    gradeFeel: 'soft',
    qualityStars: 5,
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 3, balance: 2, koordination: 4, flexibilitaet: 2 },
    createdAt: '2026-09-02T16:35:00Z',
    updatedAt: '2026-09-02T16:35:00Z',
  },
  {
    id: 'rating-2',
    boulderId: 'boulder-existing-1',
    userId: 'admin-minimum',
    userNickname: 'AdminMinimum',
    gradeFeel: 'fair',
    qualityStars: 4,
    radar: { maximalkraft: 5, kraftausdauer: 3, kraft: 5, technik: 3, balance: 3, koordination: 4, flexibilitaet: 2 },
    createdAt: '2026-09-03T11:20:00Z',
    updatedAt: '2026-09-03T11:20:00Z',
  },
  {
    id: 'rating-3',
    boulderId: 'boulder-existing-1',
    userId: 'admin-6aplus',
    userNickname: 'Admin6APlus',
    gradeFeel: 'soft',
    qualityStars: 4,
    radar: { maximalkraft: 3, kraftausdauer: 3, kraft: 3, technik: 3, balance: 2, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-09-03T18:50:00Z',
    updatedAt: '2026-09-03T18:50:00Z',
  },
  {
    id: 'rating-4',
    boulderId: 'boulder-existing-2',
    userId: 'schrauber-minimum',
    userNickname: 'Schrauber Minimum',
    gradeFeel: 'stiff',
    qualityStars: 5,
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 5, balance: 4, koordination: 3, flexibilitaet: 4 },
    createdAt: '2026-09-02T19:05:00Z',
    updatedAt: '2026-09-02T19:05:00Z',
  },
  // 6a Plus Ratings
  {
    id: 'rating-6a-1',
    boulderId: 'boulder-6a-ueberhang-onemove',
    userId: 'user-boris',
    userNickname: 'Boris',
    gradeFeel: 'fair',
    qualityStars: 5,
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 4, balance: 3, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-09-05T14:05:00Z',
    updatedAt: '2026-09-05T14:05:00Z',
  },
  {
    id: 'rating-6a-2',
    boulderId: 'boulder-6a-ueberhang-onemove',
    userId: 'hans-kletterer',
    userNickname: 'HansDereinfacheKletterer',
    gradeFeel: 'soft',
    qualityStars: 4,
    radar: { maximalkraft: 4, kraftausdauer: 3, kraft: 4, technik: 3, balance: 3, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-09-05T16:35:00Z',
    updatedAt: '2026-09-05T16:35:00Z',
  },
  {
    id: 'rating-6a-3',
    boulderId: 'boulder-6a-ueberhang-hartesding',
    userId: 'user-boris',
    userNickname: 'Boris',
    gradeFeel: 'stiff',
    qualityStars: 5,
    radar: { maximalkraft: 5, kraftausdauer: 4, kraft: 5, technik: 5, balance: 2, koordination: 3, flexibilitaet: 4 },
    createdAt: '2026-09-05T14:20:00Z',
    updatedAt: '2026-09-05T14:20:00Z',
  },
  {
    id: 'rating-6a-4',
    boulderId: 'boulder-6a-ueberhang-rot',
    userId: 'user-boris',
    userNickname: 'Boris',
    gradeFeel: 'fair',
    qualityStars: 5,
    radar: { maximalkraft: 4, kraftausdauer: 4, kraft: 4, technik: 4, balance: 3, koordination: 4, flexibilitaet: 3 },
    createdAt: '2026-09-05T15:05:00Z',
    updatedAt: '2026-09-05T15:05:00Z',
  },
];

// -------------------------------------------------------------
// Seed CRUD Boulders (Feature 1 Demo Data)
// -------------------------------------------------------------
export const SEED_CRUD_BOULDERS: BoulderInput[] = [
  {
    name: 'Rainbow Rocket',
    location: 'Fontainebleau',
    sector: 'Cuvier Rempart',
    date: '2026-09-02',
    gradeScale: 'font',
    grade: '8A',
    ascentStyle: 'top',
    attempts: 14,
    wallAngle: 'vertical',
    holdTypes: ['sloper', 'crimp'],
    perceivedDifficulty: 'fair',
    rating: 5,
    cruxDescription: 'Dynamischer Weitsprung von der Untergriff-Leiste auf die abgerundete Sloper-Kante. Volle Körperspannung beim Abfangen.',
    notes: 'Klassischer Weltklasse-Dyno. Perfektes Reibungswetter bei 12°C.',
    tags: ['dyno', 'highball', 'classic'],
  },
  {
    name: 'Karma',
    location: 'Fontainebleau',
    sector: 'Cuvier Rempart',
    date: '2026-09-02',
    gradeScale: 'font',
    grade: '7A+',
    ascentStyle: 'flash',
    attempts: 1,
    wallAngle: 'vertical',
    holdTypes: ['sloper', 'pinch'],
    perceivedDifficulty: 'soft',
    rating: 5,
    cruxDescription: 'Präziser Schulterzug und anschließender Mantle.',
    notes: 'Flash gelungen dank perfekter Beta von Jonas!',
    tags: ['sloper', 'mantle'],
  },
  {
    name: 'Dach-Projekt 42',
    location: 'Minimum Zürich',
    sector: 'Wettkampf-Dach',
    date: '2026-09-04',
    gradeScale: 'font',
    grade: '7C',
    ascentStyle: 'project',
    attempts: 7,
    wallAngle: 'roof',
    holdTypes: ['pinch', 'crimp', 'volume'],
    perceivedDifficulty: 'hard',
    rating: 4,
    cruxDescription: 'Toe-Hook halten während weitem Zug auf die linke Zange. Beim Hook-Release nicht von der Wand abreißen.',
    notes: 'Sequenz bis Zug 5 steht stabil. Nächstes Mal Ausstieg probieren.',
    tags: ['roof', 'toehook', 'project'],
  },
];
